#!/usr/bin/env node
/**
 * Compose agent context files from AGENT.md + agent-rules + role-specific tails.
 * Usage: node scripts/compose-context.mjs [--check]
 *
 * Resolves the repo root as the directory that contains `.github/agent-manifest.json`
 * (walks up from cwd), or uses SEOS_ROOT / the first CLI path argument.
 */
import { readFile, writeFile, mkdir, access } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const GENERATED_HEADER =
  "<!-- AUTO-GENERATED by npm run agent:compose — edit AGENT.md, agent-rules/, or agent-overrides/ instead -->\n\n";

async function pathExists(path) {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

async function findRepoRoot(startDir) {
  let dir = resolve(startDir);
  for (;;) {
    if (await pathExists(join(dir, ".github", "agent-manifest.json"))) {
      return dir;
    }
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return null;
}

async function readRoot(root, relativePath) {
  return readFile(join(root, relativePath), "utf-8");
}

function stripTopHeading(markdown) {
  return markdown.replace(/^#\s+.+\n+/, "");
}

async function composeEntry(root, manifest, outputPath, entry) {
  const parts = [GENERATED_HEADER, entry.title + "\n"];

  if (entry.includeAgentGuide) {
    const agent = await readRoot(root, manifest.agentGuide);
    parts.push("---\n\n## Repository guide\n\n", stripTopHeading(agent));
  }

  for (const ruleName of entry.rules ?? []) {
    const ruleFile = ruleName.endsWith(".md") ? ruleName : `${ruleName}.md`;
    const rulePath = join(manifest.rulesDir, ruleFile);
    const ruleContent = await readFile(join(root, rulePath), "utf-8");
    parts.push("\n---\n\n", ruleContent.trim(), "\n");
  }

  if (entry.tail) {
    const tailContent = await readFile(
      join(root, manifest.overridesDir, entry.tail),
      "utf-8"
    );
    parts.push("\n---\n\n", tailContent.trim(), "\n");
  }

  return { outputPath, content: parts.join("").trimEnd() + "\n" };
}

export async function composeContext({ root, checkMode = false } = {}) {
  const repoRoot =
    root ||
    process.env.SEOS_ROOT ||
    (await findRepoRoot(process.cwd())) ||
    join(dirname(fileURLToPath(import.meta.url)), "../..");

  const manifestPath = join(repoRoot, ".github/agent-manifest.json");
  const manifest = JSON.parse(await readFile(manifestPath, "utf-8"));
  const results = [];

  for (const [outputPath, entry] of Object.entries(manifest.outputs)) {
    const { content } = await composeEntry(repoRoot, manifest, outputPath, entry);
    const fullPath = join(repoRoot, outputPath);

    if (checkMode) {
      let existing;
      try {
        existing = await readFile(fullPath, "utf-8");
      } catch {
        throw new Error(
          `Missing composed file: ${outputPath} — run npm run agent:compose`
        );
      }
      if (existing !== content) {
        throw new Error(
          `Drift detected: ${outputPath} — run npm run agent:compose`
        );
      }
      results.push(outputPath);
      continue;
    }

    await mkdir(dirname(fullPath), { recursive: true });
    await writeFile(fullPath, content, "utf-8");
    results.push(outputPath);
  }

  return { root: repoRoot, outputs: results, checkMode };
}

async function main() {
  const checkMode = process.argv.includes("--check");
  const pathArg = process.argv.find(
    (a, i) => i >= 2 && !a.startsWith("-") && a !== "--check"
  );
  const { outputs, checkMode: checking } = await composeContext({
    root: pathArg ? resolve(pathArg) : undefined,
    checkMode,
  });

  if (checking) {
    console.log(`All ${outputs.length} composed context files are up to date.`);
  } else {
    for (const outputPath of outputs) {
      console.log("Composed", outputPath);
    }
  }
}

const isMain =
  process.argv[1] &&
  resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));

if (isMain) {
  main().catch((err) => {
    console.error(err.message || err);
    process.exit(1);
  });
}
